fullnameOverride: ""
deploymentType: dev # dev | local | cloud
replicaCount: 1
global:
  enableMetrics: false

Ingress:
  className: "nginx" # nginx | traefik-v2 | traefik-v3 | istio-gateway
  host: "local.infogrep.ai"

# -- Ai Service overrides
AiService:
  ollamaCreate: false
  env:
    openaiKey: "placeholder"
    ollamaUrl: "host.minikube.internal:11434"
  service:
    type: ClusterIP
  image:
    tag: latest
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

# -- Auth Service overrides
AuthService:
  env:
    CLIENT_ID: ""
    CLIENT_SECRET: "" 
    DOMAIN: ""
    APP_SECRET_KEY: ""
    REDIRECT_URI: ""
    FRONTEND_LOGIN_URI: ""
  service:
    type: ClusterIP
  image:
    tag: latest
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi

# -- Chatroom Service overrides
ChatroomService:
  service:
    type: ClusterIP
  image:
    tag: latest
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi

# -- File Management Service overrides
FileManagementService:
  service:
    type: ClusterIP
  image:
    tag: latest
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi

# -- UI service overrides
InfogrepFrontend:
  create: true
  service:
    type: LoadBalancer
  image:
    tag: latest
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1.5Gi
  
# -- Milvus overrides
MilvusConfig:
  serviceType: ClusterIP
  standaloneReplica: 1
  env:
    username: "infogrep"
    password: "placeholder"
    rootPassword: "placeholder"

# -- Elasticsearch overrides
ElasticsearchConfig:
  replicaCount: 1
  defaultPodSpec: true

# -- Kibana overrides
KibanaConfig:
  replicaCount: 1
  serviceType: "NodePort"
  defaultPodSpec: true

InfogrepPostgres:
  replicaCount: 2
  postgresService:
    ro-enabled: true
    r-enabled: true
  env:
    username: "postgres"
    password: "placeholder"