fullnameOverride: ""
deploymentType: dev
replicaCount: 1
global:
  enableMetrics: false

Ingress:
  className: "nginx"
  host: "local.infogrep.ai"

# -- Ai Service overrides
AiService:
  ollamaCreate: "false"
  env:
    openaiKey: "placeholder"
    ollamaUrl: "host.minikube.internal:11434"
  service:
    type: ClusterIP

# -- Auth Service overrides
AuthService:
  env:
    CLIENT_ID: ""
    CLIENT_SECRET: "" 
    DOMAIN: ""
    APP_SECRET_KEY: ""
    REDIRECT_URI: ""
    FRONTEND_LOGIN_URI: ""
  service:
    type: ClusterIP

ChatroomService:
  service:
    type: ClusterIP

FileManagementService:
  service:
    type: ClusterIP

# -- Milvus overrides
MilvusConfig:
  serviceType: ClusterIP
  standaloneReplica: 1
  env:
    username: "infogrep"
    password: "placeholder"
    rootPassword: "placeholder"

# -- Elasticsearch overrides
ElasticsearchConfig:
  replicaCount: 1
  defaultPodSpec: "true"

# -- Kibana overrides
KibanaConfig:
  replicaCount: 1
  serviceType: "NodePort"
  defaultPodSpec: "true"

InfogrepPostgres:
  replicaCount: 2
  postgresService:
    ro-enabled: "true"
    r-enabled: "true"
  env:
    username: "postgres"
    password: "placeholder"