fullnameOverride: ""
deploymentType: local
replicaCount: 1

# -- Ai Service overrides
AiService:
  ollamaCreate: "false"
  env:
    openaiKey: ""
    ollamaUrl: ""
  service:
    type: ClusterIP

# -- Auth Service overrides
AuthService:
  env:
    CLIENT_ID: ""
    CLIENT_SECRET: "" 
    DOMAIN: ""
    APP_SECRET_KEY: ""
    REDIRECT_URI: ""
    FRONTEND_LOGIN_URI: ""
  service:
    type: ClusterIP

ChatroomService:
  service:
    type: ClusterIP

FileManagementService:
  service:
    type: ClusterIP

# -- Milvus overrides
MilvusConfig:
  serviceType: ClusterIP
  standaloneReplica: 1
  env:
    username: "infogrep"
    password: ""
    rootPassword: ""

# -- Elasticsearch overrides
ElasticsearchConfig:
  replicaCount: 1
  defaultPodSpec: "true"

# -- Kibana overrides
KibanaConfig:
  replicaCount: 1
  serviceType: "NodePort"
  defaultPodSpec: "true"

InfogrepPostgres:
  replicaCount: 2
  postgresService:
    ro-enabled: "true"
    r-enabled: "true"
  env:
    username: "postgres"
    password: ""