apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "infogrep.videoService.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "infogrep.labels" (dict "context" . "component" .Values.VideoService.name "name" .Values.VideoService.name) | nindent 4 }}
spec:
  {{- if .Values.VideoService.replicaCount }}
  replicas: {{ .Values.VideoService.replicaCount }}
  {{- else }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "infogrep.selectorLabels" (dict "context" . "name" .Values.VideoService.name) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "infogrep.labels" (dict "context" . "component" .Values.VideoService.name "name" .Values.VideoService.name) | nindent 8 }}
    spec:
      serviceAccountName: {{ include "infogrep.videoService.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.VideoService.serviceAccount.automountServiceAccountToken }}
    {{- with .Values.VideoService.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Values.VideoService.name }}
          env:
            - name: OPENAI_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secrets
                  key: openaiKey
                  optional: false
            - name: SERPAPI_KEY
              valueFrom:
                secretKeyRef:
                  name: serpapi-secret
                  key: serpapiKey
                  optional: false
          image: "{{ .Values.VideoService.image.repository }}:{{ .Values.VideoService.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.VideoService.image.pullPolicy }}
          resources:
            {{- toYaml .Values.VideoService.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.VideoService.containerPorts.server }}
