# Default values for infogrep.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Provide a name in place of `infogrep`
nameOverride: infogrep
# -- String to fully override `"infogrep.fullname"`
fullnameOverride: ""
# -- Override the Kubernetes version, which is used to evaluate certain manifests
kubeVersionOverride: ""
# Override APIVersions
# If you want to template helm charts but cannot access k8s API server
# you can set api versions here
apiVersionOverrides: {}
replicaCount: 1
namespace: infogrep
domain: local.infogrep.ai

AiService:
  name: ai-service

  # -- Default namespace
  namespace: ""

  # -- GHCR Config
  image:
    repository: ghcr.io/se-exort/ai-service
    pullPolicy: IfNotPresent
    tag: latest
  
  # -- GHCR Image Pull Secret
  imagePullSecrets:
    - name: ghcr
  
  # -- Service Account
  serviceAccount:
    create: true
    name: ai-service-account
    annotations: {}
    labels: {}
    automountServiceAccountToken: true
  
  # -- Container Ports
  containerPorts:
    server: 8004

  # -- Resource Limits
  resources:
   limits:
      cpu: 500m
      memory: 1Gi
   requests:
      cpu: 500m
      memory: 512Mi

  # -- K8s Service Configuration
  service:
    annotations: {}
    labels: {}
    type: NodePort
    nodePortHttp: 30080
    servicePortHttp: 8004
    servicePortHttpName: ai-service-port
    servicePortHttpsAppProtocol: ""
    loadBalancerClass: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    externalIPs: []
    externalTrafficPolicy: Cluster
    sessionAffinity: None

  # -- Ingress configuration
  ingress:
    enabled: true
    controller: generic
    labels: {}
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      kubernetes.io/ingress.class: "nginx"
    ingressClassName: nginx
    hostname: ""
    # -- The path to Argo CD server
    path: /
    # -- Ingress path type. One of `Exact`, `Prefix` or `ImplementationSpecific`
    pathType: Prefix
    tls: false
    extraHosts: []
    extraPaths: []
    extraRules: []
    extraTls: []