apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ template "infogrep.elasticsearchService.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "infogrep.labels" (dict "context" . "component" .Values.ElasticsearchConfig.name "name" .Values.ElasticsearchConfig.name) | nindent 4 }}
spec:
  version: 8.17.1
  nodeSets:
  - name: default
    count: {{ .Values.ElasticsearchConfig.replicaCount }}
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.ElasticsearchConfig.pvSize }}
        storageClassName: standard
    config:
      node.store.allow_mmap: false
    {{- if eq .Values.ElasticsearchConfig.defaultPodSpec "false"}}
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            {{- toYaml .Values.ElasticsearchConfig.resources | nindent 12 }}
    {{- end }}