apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "infogrep.labels" (dict "context" . "component" .Values.AuthService.name "name" "auth-service-secret") | nindent 4 }}
type: Opaque
data:
  {{- with .Values.AuthService.env }}
  client_id: {{ .CLIENT_ID | b64enc }}
  client_secret: {{ .CLIENT_SECRET | toString | b64enc }}
  domain: {{ .DOMAIN | b64enc }}
  app_secret_key: {{ .APP_SECRET_KEY | quote | b64enc }}
  redirect_uri: {{ .REDIRECT_URI | b64enc }}
  frontend_login_uri: {{ .FRONTEND_LOGIN_URI | b64enc }}
  {{- end }}
