apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-etcd-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "infogrep.labels" (dict "context" . "component" .Values.VectorEtcd.name "name" "vector-etcd-configs") | nindent 4 }}
data:
  autoCompactionMode: {{ .Values.VectorEtcd.env.ETCD_AUTO_COMPACTION_MODE }}
  autoCompactionRetention: {{ .Values.VectorEtcd.env.ETCD_AUTO_COMPACTION_RETENTION | quote }}
  quotaBackendBytes: {{ .Values.VectorEtcd.env.ETCD_QUOTA_BACKEND_BYTES | quote }}