apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "infogrep.labels" (dict "context" . "component" "infogrep-namespace" "name" "namespace") | nindent 4 }}
    istio-injection: enabled
