apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: {{ template "infogrep.milvus.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: milvus
    {{- include "infogrep.labels" (dict "context" . "component" .Values.MilvusConfig.name "name" .Values.MilvusConfig.name) | nindent 4 }}
spec:
  config:
    common:
      security:
        authorizationEnabled: true
  components:
    standalone:
      replicas: {{ .Values.MilvusConfig.standaloneReplica }}
      serviceType: {{ .Values.MilvusConfig.serviceType }}
  dependencies:
    etcd:
      inCluster:
        values:
          replicaCount: {{ .Values.MilvusEtcdConfig.replicaCount }}
          resources:
            {{- toYaml .Values.MilvusEtcdConfig.resources | nindent 12 }}
          persistence:
            enabled: true
            storageClass: {{ .Values.MilvusEtcdConfig.persistence.storageClass }}
            size: {{ .Values.MilvusEtcdConfig.persistence.size }}
            {{- with .Values.MilvusEtcdConfig.persistence.accessModes }}
            accessModes:
            {{- toYaml . | nindent 12 }}
            {{- end }}
        deletionPolicy: Delete
        pvcDeletion: false
    storage:
      inCluster:
        values:
          mode: standalone
          resources:
            {{- toYaml .Values.MilvusConfig.resources | nindent 12 }}
          persistence:
            enabled: true
            storageClass: {{ .Values.MilvusConfig.persistence.storageClass }}
            size: {{ .Values.MilvusConfig.persistence.size }}
            {{- with .Values.MilvusConfig.persistence.accessModes }}
            accessModes:
            {{- toYaml . | nindent 12 }}
            {{- end }}
 