apiVersion: v1
kind: Secret
metadata:
  name: infogrep-milvus-creds
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "infogrep.labels" (dict "context" . "component" .Values.MilvusConfig.name "name" "infogrep-milvus-creds") | nindent 4 }}
type: Opaque
data:
  {{- with .Values.MilvusConfig.env.username }}
  username: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.MilvusConfig.env.password }}
  password: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.MilvusConfig.env.rootPassword }}
  rootPassword: {{ . | b64enc }}
  {{- end }}
