apiVersion: v1
kind: Secret
metadata:
  name: openai-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "infogrep.labels" (dict "context" $) | nindent 4 }}
type: Opaque
data:
  {{- with .Values.KeyConfig.openaiKey }}
  openaiKey: {{ . | b64enc }}
  {{- end }}
